### PR TITLE
Support for different device types + template refactoring

### PR DESCRIPTION
**Pull request by stklcode**
I've added a node attribute `devtype` to specify the type of device emultaed by the bridge.

Defaults to _Extended Color Light_ (LCT007) with full RGBW controls.
In addition, a node can be _Color Temperature Light_ (LTW012) with only color temperature support or _Dimmable Light_ (LWB007) without only brightness control.

nodered-echo-devicetypes

The API reports an error if an unsupprted mode is requested, i.e. changing hue/sat on a CT-light, s.t. the echo correctly responds with "... does not support this".

To not duplicate the JSON templates I introduced model classes that represent the state and dynamically generate the global state element. The model classes are somewhat intelligent and know their types. Example creation for an extended spec including capabilities:
```javascript
const state = new State(d.on, d.bri, d.hue, d.sat, d.ct, d.colormode);
const Info.forRGBW('Device Name', state).extended().withCapabilities(Capabilities.forRGBW());
```

### CODE REVIEW

**Comment by Barabba11** [comment]
Hi mate, thanks for your work :)
I don't know if it's interesting for you, if you have mutiple echos and want to use the same device generic name, for example "switch on the light", we need support on this feature too.. thank you )

**Comment by stklcode** [comment]
Not necessarily related to my changes, but at least the new dynamic model could make it little easier.

* add another optional field like "echoID" to the device nodes
* rework the API endpoints s.t. the "username" is passed to the getDevices() / getDevice() method
* rework getDevices() to ignore devices assigned to other Echoes

Update registration endpoint, s.t.
* each device is registered with a custom ID (can be random) instead of fixed dummy
* for better UX remember probably remember timestamp and last IP in ObjectDB
* generate a select box to easily assign registered Echoes to devices

(should be discussed in a new issue though)

**Comment by Barabba11** [comment]
Thanks for kind answer, do you evaluate to introduce it too? I'm not an expert of javascript and for me "the mountain is too high to climb it" :( in this case I thank you in advance :)
Maybe with echoID is possible to filter, but we need to know before which is the ID of echo, how to do that? Maybe add one device as example, know it and after do the job. With IP is easier, we can check it on router as DCHP leases. Anyway for me is not a problem.
The filter should work also during discovery, the device should comunicate only with that specific Echo. Create a custom ID is also important, as the chance to store it on the flow backup, so when we restore the flow from backup we don't need to delete all devices in Alexa and recognize again devices.

**Comment by a-bailey** [comment]
Nice work man, when I look at the alexa discovery interface it doesn't seem to hard to also add devices like thermostats which support "raise" and "lower" commands is there an inherent issue I'm not seeing?  I wanted to build something like that but it would make sense to integrate in this already existing node

**Comment by gnuhel** [comment]
@stklcode Hey, when can we expect this PR to be merged?

**Comment by stklcode** [comment]
It's not my project and I'm no team member, so I personally am not able to make any decision on that.

I've updated my PR to the latest changes in _master_ (unit tests passing) and as the PR is not marked as draft, it could be ready to merge from my point of view.

I know my changes probably go far deeper than necessary. However I have not received any feedback on the implementation so far. Hence I cannot tell if the way how things are done is even remotely in the interest of @datech

**Comment by datech** [comment]
Stefan, 

Thanks for the pull request. I didn't have time to review and merge it, as it is quite large. I hope I will find some time soon to analyze it.

**Comment by Barabba11** [comment]
Teodor, if you think that is not too complicated to get from server the IP address of the Echo device, may you kindly introduce on version 2.0 a filter by IP? I wonder ask simply match with the one specified in HUB options, and if it's not that source discard the packet and don't elaborate it (in options would be checked as default "accept all connections" so nobody will suffer troubles). 
Thank you a lot!

**Comment by joachimmarder** [comment]
@stklcode: This PR did not make it into an official release yet, right?

**Pull request merged**
